CREATE SCHEMA `telefonia`;

CREATE TABLE `telefonia`.`endereco` (
  `ID` int NOT NULL,
  `RUA` varchar(255) NOT NULL,
  `CEP` varchar(8) NOT NULL,
  `BAIRRO` varchar(255) NOT NULL,
  `CIDADE` varchar(255) NOT NULL,
  `ESTADO` varchar(2) NOT NULL,
  `NUMERO` varchar(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID` ASC) VISIBLE)
)


CREATE TABLE `telefonia`.`telefone` (
  `ID` INT NOT NULL,
  `DDD` VARCHAR(3) NOT NULL,
  `NUMERO` VARCHAR(9) NOT NULL,
  `ATIVO` TINYINT NOT NULL,
  `MOVEL` TINYINT NOT NULL,
  `ID_CLIENTE` INT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE);

  
  CREATE TABLE `telefonia`.`cliente` (
  `ID` INT NOT NULL,
  `NOME` VARCHAR(255) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `ATIVO` TINYINT NOT NULL,
  `ID_ENDERECO` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  INDEX `ID_ENDERECO_idx` (`ID_ENDERECO` ASC) VISIBLE,
  CONSTRAINT `ID_ENDERECO`
    FOREIGN KEY (`ID_ENDERECO`)
    REFERENCES `telefonia`.`endereco` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
